version: "3"
services:

  base-agent:
    build: ./
    image: dcagatay/azp-agent-dind:latest
    privileged: true
    environment:
      AZP_URL: "https://dev.azure.com/xxxyyzzz"
      AZP_TOKEN: ""
      AZP_AGENT_NAME: "my-agent"
      # AZP_WORK: "_work"
      # AZP_POOL:	"Default"
