version: "3"
services:
  base-agent:
    build:
      context: .
      args:
        AGENT_VERSION: ${AGENT_VERSION:-2.200.2}
    image: dcagatay/azp-agent-dind:${AGENT_VERSION:-latest}
    privileged: true
    environment:
      AZP_URL: "https://dev.azure.com/xxxyyzzz"
      AZP_TOKEN: ""
      AZP_AGENT_NAME: "my-agent"
      # AZP_WORK: "_work"
      # AZP_POOL:	"Default"
