name: ci
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docker-compose.yml'
      - 'check-agent-releases.sh'
      - '.github/workflows/build-push-latest-version.yml'
    branches:
      - 'releases/**'

jobs:

  bake-version:
    strategy:
      matrix:
        version:
          - 2.192.0
          - 2.191.1
          - 2.190.0
          - 2.189.0
          - 2.188.4
          - 2.188.3
          - 2.187.2
          - 2.186.1
          - 2.185.1
          - 2.184.2
          - 2.183.1
          - 2.182.1
          - 2.181.2
          - 2.181.1
          - 2.181.0
          - 2.179.0
          - 2.177.1
          - 2.175.2
          - 2.174.3
          - 2.174.2
          - 2.174.1
          - 2.173.0
          - 2.172.2
          - 2.172.1
          - 2.171.1
          - 2.170.1
          - 2.169.1
          - 2.168.2
          - 2.166.4
          - 2.166.3
          - 2.165.2
          - 2.165.0
          - 2.164.8
          - 2.164.7
          - 2.164.6
          - 2.163.1
          - 2.162.0
          - 2.160.1
          - 2.160.0
          - 2.159.2
          - 2.158.1
          - 2.158.0
          - 2.155.1
          - 2.154.3
          - 2.153.2
          - 2.152.1

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
        env:
          AGENT_VERSION: ${{ matrix.version }}

  bake-latest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@master
        with:
          push: true

