name: ci
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docker-compose.yml'
      - 'check-agent-releases.sh'
      - '.github/workflows/build-push-all-versions.yml'
    branches:
      - master

jobs:

  bake-latest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest
        uses: docker/bake-action@master
        with:
          targets: latest
          push: true

  bake-version:
    needs: bake-latest
    strategy:
      matrix:
        version:
          - 2.192.0
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
        env:
          AGENT_VERSION: ${{ matrix.version }}
