name: ci
on:
  schedule:
    - cron: '30 6 5 * *' # Run monthly
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docker-compose.yml'
      - 'check-agent-releases.sh'
      - '.github/workflows/build-push-all-versions.yml'
    branches:
      - master

jobs:
  provide_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Install xmllint
        run: sudo apt-get install -y curl jq
      - id: output_data
        run: echo "::set-output name=matrix::$(NUM_RELEASES=2 ./check-agent-releases.sh | jq  --raw-input . | jq --slurp .)"
    # this step is needed, so the output gets to the next defined job
    outputs:
        matrix: ${{ steps.output_data.outputs.matrix }}

  bake-latest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest
        uses: docker/bake-action@master
        with:
          targets: latest,version
          push: true
        env:
          AGENT_VERSION: ${{ matrix.version }}

    strategy:
      fail-fast: false
      matrix:
          version: ${{fromJson(needs.provide_matrix.outputs.matrix)}}
