name: build-push-latest-version
on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 5 * *" # Run monthly
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docker-compose.yml"
    branches:
      - master

jobs:
  # provide_matrix:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Install curl and jq
  #       run: sudo apt-get install -y curl jq
  #     - name: Install gather Azure Devops Agent versions from API
  #       run: |
  #         echo '{"version": '$(NUM_RELEASES=2 ./check-agent-releases.sh | jq  --raw-input . | jq --slurp -c . )'}' > versions.txt
  #         cat ./versions.txt
  #     - id: output_data
  #       run: echo "::set-output name=matrix::$(cat ./versions.txt)"
  #     - name: print set data
  #       run: echo ${{steps.output_data.outputs.matrix}}
  #     - name: print debug data
  #       run: 'echo "::debug:: ${{steps.output_data.outputs.matrix}}"'
  #   # this step is needed, so the output gets to the next defined job
  #   outputs:
  #     matrix: ${{steps.output_data.outputs.matrix}}

  bake-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Install curl and jq
        run: sudo apt-get install -y curl jq
      - name: Install gather Azure Devops Agent versions from API
        id: version_provider
        run: |
          echo "::set-output name=version::$(NUM_RELEASES=2 ./check-agent-releases.sh | jq  --raw-input . | jq --slurp -c . )"
      - name: debug
        run: |
          echo "::debug:: ${{steps.version_provider.outputs.version}}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            dcagatay/azp-agent-dind:latest
            dcagatay/azp-agent-dind:${{steps.version_provider.outputs.version}}
          build-args: |
            AGENT_VERSION=${{steps.version_provider.outputs.version}}

      # - name: Build and push latest
      #   uses: docker/bake-action@master
      #   with:
      #     targets: latest,version
      #     push: true
      #   env:
      #     AGENT_VERSION: ${{steps.version_provider.outputs.version}}


          # AGENT_VERSION: ${{ matrix.version }}

    # strategy:
    #   # matrix:
    #   #   version:
    #   #     - 2.200.2
    #   matrix: ${{fromJson(needs.provide_matrix.outputs.matrix)}}
